[package]
name = "cidrwall-ebpf"
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "XDP and TCX filtering programs for cidrwall"
repository = "https://github.com/joshtgl/cidrwall"

[features]
default = []
xdp-program = ["dep:aya-ebpf", "dep:cidrwall-common"]
tc-program = ["dep:aya-ebpf", "dep:cidrwall-common"]

[dependencies]
aya-ebpf = { version = "0.2.1", optional = true }
cidrwall-common = { version = "=0.2.0", path = "../cidrwall-common", optional = true }

[lib]
path = "src/lib.rs"

[[bin]]
name = "cidrwall-xdp"
path = "src/xdp.rs"
test = false
bench = false
required-features = ["xdp-program"]

[[bin]]
name = "cidrwall-tc"
path = "src/tc.rs"
test = false
bench = false
required-features = ["tc-program"]
